swagger: '2.0'
info:
  version: "1.0.0"
  title: "WINE API"
  description: ""
basePath: "/v1"
schemes:
- http
paths:
  /sayHello/{name}:
    get:
      summary: "Inventory Adjustment payload"
      description: "Get the Inventory Adjustment payload for MERCH"
      produces:
      - "application/json"
      parameters:
      - in: "path"
        name: "name"
        type: "string"
        required: true
        description: "the event id"
      responses:
        200:
          description: "Success"
          schema:
            $ref: "#/definitions/Response"
        401:
          description: "Unauthorized"

definitions:
  Response:
    type: object
    properties:
      name:
        type: string